[package]
name = "bonbon"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
bs58 = "0.4.0"
mpl-token-metadata = "1.2.5"
solana-account-decoder = "=1.10.9"
solana-sdk = "=1.10.9"
solana-transaction-status = "=1.10.9"
spl-token = "3.2.0"
